### ISSUE TITLE
Search bar is always accessable

### ISSUE THREAD

**Issue by OffifialMITX** [BennyKok/OpenLauncher#36]
Like [here](https://drive.google.com/file/d/0B8HcTODSY2XzMWxMU0l4Zmg3dkk/view?usp=sharing).

**Comment by dkanada** [comment]
Could you explain specifically what you think is wrong? There are issues with the search bar on certain versions of Android, do you mean you can't disable the search bar in the settings or are you having a different issue?

similar to #33

**Comment by OffifialMITX** [comment]
Sorry, I thought the video is clear enough. The issue is that I can activate and type into the search bar even if it's not visible. I doesn't happen always but pretty often and it seems like there's a connection to the full screen setting.

**Comment by dkanada** [comment]
I am actually not sure how the search bar is supposed to behave since I have a similar issue. I just turned it off since I normally don't use a search bar. Mine does not show a keyboard when clicked, and I am not sure if it is supposed to show as transparent or not.

![screenshot_20170329-150050](https://cloud.githubusercontent.com/assets/21353219/24476604/2a9a0462-1491-11e7-8b4f-3d1f1cb78d92.png)

**Comment by BennyKok** [comment]
right, so many bugs.
